/* MedStat Lab - client-side medical statistics toolkit */
const state = { data: [], columns: [], fileName: "", results: [], charts: {} };

const esc = s => String(s ?? "").replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num = v => { const n = Number(String(v).replace(/,/g,'')); return Number.isFinite(n) ? n : null; };
const vals = col => state.data.map(r=>num(r[col])).filter(v=>v!==null);
const isNumeric = col => { const a=state.data.map(r=>r[col]).filter(v=>v!==""&&v!=null); return a.length>0 && a.filter(v=>num(v)!==null).length/a.length>=.8; };
const uniq = col => [...new Set(state.data.map(r=>String(r[col]??"").trim()).filter(Boolean))];
const mean = a => a.length ? a.reduce((x,y)=>x+y,0)/a.length : NaN;
const variance = a => { const m=mean(a); return a.length>1 ? a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1):NaN; };
const sd = a => Math.sqrt(variance(a));
const median = a => { if(!a.length)return NaN; const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2; };
const quantile=(a,q)=>{const b=[...a].sort((x,y)=>x-y);if(!b.length)return NaN;const p=(b.length-1)*q,i=Math.floor(p),f=p-i;return b[i]+(b[i+1]-b[i]||0)*f};
const fmt=x=>Number.isFinite(x)?(Math.abs(x)>=100?x.toFixed(1):x.toFixed(3)):"—";
const pFmt=p=>Number.isFinite(p)?(p<.001?"<0.001":p.toFixed(3)):"—";
const erf=x=>{const s=x<0?-1:1,a=Math.abs(x),t=1/(1+.3275911*a),y=1-((((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-a*a);return s*y};
const normalP=z=>1-(1+erf(Math.abs(z)/Math.SQRT2))/2;
function tP(t,df){try{return 2*(1-jStat.studentt.cdf(Math.abs(t),df))}catch{return 2*normalP(t)}}
function chiP(x,df){try{return 1-jStat.chisquare.cdf(x,df)}catch{return NaN}}
function renderTable(el, headers, rows){el.innerHTML=`<thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody>`}

function controls(type){
  const cols=state.columns, nums=cols.filter(isNumeric);
  const select=(id,arr,placeholder)=>`<select id="${id}"><option value="">${placeholder}</option>${arr.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join("")}</select>`;
  if(!state.data.length) return `<div class="empty">Upload a dataset first in <b>Data Import</b>.</div>`;
  const common={dictionary:`<div class="panel-head"><h2>Variable dictionary</h2><button class="ghost" id="refreshTool">Refresh</button></div><div class="table-wrap"><table id="toolTable"></table></div>`,
  cleaning:`<div class="cards three"><div class="action-card"><h3>Remove duplicate rows</h3><p>Removes exact duplicate records from the working dataset.</p><button class="primary" id="dedupe">Remove duplicates</button></div><div class="action-card"><h3>Trim text</h3><p>Trims leading/trailing spaces from all text fields.</p><button class="primary" id="trimText">Trim text</button></div><div class="action-card"><h3>Remove empty columns</h3><p>Removes columns with no observed values.</p><button class="primary" id="emptyCols">Remove empty columns</button></div></div><div class="panel"><div class="panel-head"><h2>Missingness</h2></div><div class="table-wrap"><table id="cleanTable"></table></div></div>`,
  validation:`<div class="toolbar">${select("validCol",cols,"All variables")}<input id="minVal" type="number" placeholder="Minimum (optional)"><input id="maxVal" type="number" placeholder="Maximum (optional)"><button class="primary" id="runValidation">Check</button></div><div class="panel"><div class="panel-head"><h2>Validation results</h2></div><div class="table-wrap"><table id="validTable"></table></div></div>`,
  descriptive:`<div class="toolbar">${select("descCol",cols,"Select variable")}<button class="primary" id="runDesc">Analyze</button><button class="ghost" id="allDesc">All variables</button></div><div class="panel"><div class="panel-head"><h2>Descriptive results</h2></div><div class="table-wrap"><table id="descTable"></table></div></div>`,
  normality:`<div class="toolbar">${select("normCol",nums,"Numeric variable")}<button class="primary" id="runNorm">Analyze</button></div><div id="normResult"></div><div class="chart-box"><canvas id="normChart"></canvas></div>`,
  categorical:`<div class="toolbar">${select("catA",cols,"Exposure / variable A")}${select("catB",cols,"Outcome / variable B")}<button class="primary" id="runCat">Run analysis</button></div><div id="catResult"></div>`,
  continuous:`<div class="toolbar">${select("contY",nums,"Numeric outcome")}${select("contG",cols,"Grouping variable")}<select id="contTest"><option value="auto">Auto</option><option value="ttest">Independent t-test</option><option value="mw">Mann–Whitney U</option><option value="anova">One-way ANOVA</option></select><button class="primary" id="runCont">Run analysis</button></div><div id="contResult"></div>`,
  correlation:`<div class="toolbar">${select("corrX",nums,"Variable X")}${select("corrY",nums,"Variable Y")}<select id="corrMethod"><option value="pearson">Pearson</option><option value="spearman">Spearman</option></select><button class="primary" id="runCorr">Run analysis</button></div><div id="corrResult"></div><div class="chart-box"><canvas id="corrChart"></canvas></div>`,
  linear:`<div class="toolbar">${select("linY",nums,"Continuous outcome")}${select("linX1",nums,"Predictor 1")}${select("linX2",nums,"Predictor 2 (optional)")}<button class="primary" id="runLin">Fit model</button></div><div id="linResult"></div>`,
  logistic:`<div class="toolbar">${select("logY",cols,"Binary outcome (0/1)")} ${select("logX1",nums,"Predictor 1")}${select("logX2",nums,"Predictor 2 (optional)")}<button class="primary" id="runLog">Fit model</button></div><div id="logResult"></div>`,
  poisson:`<div class="toolbar">${select("poiY",cols,"Count / binary outcome")}${select("poiX",nums,"Predictor 1")}${select("poiX2",nums,"Predictor 2 (optional)")}<button class="primary" id="runPoi">Fit model</button></div><div id="poiResult"></div>`,
  survival:`<div class="toolbar">${select("survTime",nums,"Time variable")}${select("survEvent",cols,"Event (1=event, 0=censored)")} ${select("survGroup",cols,"Group (optional)")}<button class="primary" id="runSurv">Kaplan–Meier</button></div><div id="survResult"></div><div class="chart-box tall"><canvas id="survChart"></canvas></div>`,
  diagnostic:`<div class="toolbar">${select("diagRef",cols,"Reference standard (0/1)")} ${select("diagTest",cols,"Test result (0/1)")}<button class="primary" id="runDiag">2×2 analysis</button></div><div id="diagResult"></div><div class="panel"><div class="panel-head"><h2>ROC / AUC</h2><p class="muted">Use a numeric score as the test to calculate ROC.</p></div><div class="toolbar">${select("rocRef",cols,"Reference standard (0/1)")} ${select("rocScore",nums,"Numeric test score")}<button class="primary" id="runROC">Plot ROC</button></div><div class="chart-box"><canvas id="rocChart"></canvas></div><div id="rocResult"></div></div>`,
  report:`<div class="cards three"><div class="action-card"><h3>HTML report</h3><p>Download a self-contained summary of this session.</p><button class="primary" id="downloadHtml">Download HTML</button></div><div class="action-card"><h3>Clean CSV</h3><p>Export the current working dataset.</p><button class="primary" id="downloadCsv">Download CSV</button></div><div class="action-card"><h3>Print / PDF</h3><p>Open the report and use your browser's Print → Save as PDF.</p><button class="primary" id="printReport">Open printable report</button></div></div><div class="panel"><div class="panel-head"><h2>Session results</h2></div><div id="reportResults"></div></div>`};
  return common[type]||"";
}

/* Matrix utilities for regression */
function transpose(A){return A[0].map((_,j)=>A.map(r=>r[j]));}
function mm(A,B){return A.map(r=>B[0].map((_,j)=>B.reduce((s,_,i)=>s+r[i]*B[i][j],0)));}
function inv(A){const n=A.length,M=A.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]);for(let i=0;i<n;i++){let p=i;for(let r=i+1;r<n;r++)if(Math.abs(M[r][i])>Math.abs(M[p][i]))p=r;if(Math.abs(M[p][i])<1e-12)throw Error("Singular matrix");[M[i],M[p]]=[M[p],M[i]];const d=M[i][i];M[i]=M[i].map(x=>x/d);for(let r=0;r<n;r++)if(r!==i){const f=M[r][i];M[r]=M[r].map((x,j)=>x-f*M[i][j]);}}return M.map(r=>r.slice(n));}
function ols(X,y){const Xt=transpose(X), XtX=mm(Xt,X), V=inv(XtX), b=mm(V,mm(Xt,y.map(v=>[v]))).map(r=>r[0]);const fit=X.map(r=>r.reduce((s,x,i)=>s+x*b[i],0)),res=y.map((v,i)=>v-fit[i]),df=y.length-X[0].length,s2=res.reduce((s,x)=>s+x*x,0)/df,SE=V.map((r,i)=>Math.sqrt(Math.max(0,r[i]*s2))),T=b.map((v,i)=>v/SE[i]),SST=y.reduce((s,v)=>s+(v-mean(y))**2,0),SSE=res.reduce((s,v)=>s+v*v,0);return {b,SE,T,p:T.map(t=>tP(t,df)),CI:b.map((v,i)=>[v-1.96*SE[i],v+1.96*SE[i]]),r2:1-SSE/SST,df};}
function logistic(X,y){let b=Array(X[0].length).fill(0);for(let iter=0;iter<30;iter++){const p=X.map(r=>1/(1+Math.exp(-Math.max(-30,Math.min(30,r.reduce((s,x,i)=>s+x*b[i],0))))));const W=X.map((r,i)=>r.map(x=>x*Math.max(p[i]*(1-p[i]),1e-6)));const z=p.map((pi,i)=>rSafe(y[i],pi));const Xt=transpose(X),XtWX=mm(Xt,W.map((r,i)=>r.map((x,j)=>x*X[i][j]))),rhs=mm(Xt,W.map((r,i)=>[z[i]*r[i][0]/(X[i][0]||1)])); /* replace with standard IRLS below */ 
    const w=p.map(q=>Math.max(q*(1-q),1e-6)), Xw=X.map((r,i)=>r.map(x=>x*Math.sqrt(w[i]))), yw=y.map((v,i)=>(v-p[i])*Math.sqrt(w[i]));
    const step=mm(inv(mm(transpose(Xw),Xw)),mm(transpose(Xw),yw.map(v=>[v]))).map(r=>r[0]); const nb=b.map((v,i)=>v+step[i]); if(nb.every((v,i)=>Math.abs(v-b[i])<1e-7)){b=nb;break} b=nb;
  }
  const p=X.map(r=>1/(1+Math.exp(-Math.max(-30,Math.min(30,r.reduce((s,x,i)=>s+x*b[i],0))))));const w=p.map(q=>Math.max(q*(1-q),1e-6)),V=inv(mm(transpose(X.map((r,i)=>r.map(x=>x*Math.sqrt(w[i])))),X.map((r,i)=>r.map(x=>x*Math.sqrt(w[i])))));const se=V.map((r,i)=>Math.sqrt(r[i])), z=b.map((v,i)=>v/se[i]);return {b,se,z,p:z.map(v=>2*normalP(v)),OR:b.map(Math.exp),CI:b.map((v,i)=>[Math.exp(v-1.96*se[i]),Math.exp(v+1.96*se[i])])};
}
function rSafe(y,p){return y/p-(1-y)/(1-p)}

/* Page rendering */
function installPlaceholders(){
  document.querySelectorAll("PagePlaceholder").forEach(el=>{
    const title=el.getAttribute("title"), heading=el.getAttribute("heading"), text=el.getAttribute("text"), id=el.parentElement.id.replace("page-","");
    el.outerHTML=`<div class="page-head"><div><p class="eyebrow">${esc(title)}</p><h1>${esc(heading)}</h1><p class="muted">${esc(text)}</p></div></div><div class="tool" id="tool-${id}">${controls(id)}</div>`;
  });
}
installPlaceholders();

function refreshAll(){
  document.getElementById("projectName").textContent=state.fileName||"Untitled dataset";
  document.getElementById("dataStatus").textContent=state.data.length?`${state.data.length.toLocaleString()} rows loaded`:"No data";
  document.getElementById("mRows").textContent=state.data.length;
  document.getElementById("mCols").textContent=state.columns.length;
  document.getElementById("mMissing").textContent=state.data.reduce((s,r)=>s+state.columns.filter(c=>r[c]===""||r[c]==null).length,0);
  const seen=new Set(), dup=state.data.filter(r=>{const k=JSON.stringify(r);if(seen.has(k))return true;seen.add(k);return false}).length;
  document.getElementById("mDup").textContent=dup;
  document.querySelectorAll(".tool").forEach(t=>{const type=t.id.replace("tool-",""); if(!document.getElementById("page-"+type).classList.contains("active")) return; t.innerHTML=controls(type); bindTool(type);});
  if(state.data.length) preview();
}
function bindTool(type){
  const q=id=>document.getElementById(id);
  if(type==="dictionary"){renderDictionary();q("refreshTool")?.addEventListener("click",renderDictionary);}
  if(type==="cleaning"){renderMissing();q("dedupe")?.addEventListener("click",()=>{const seen=new Set();state.data=state.data.filter(r=>{const k=JSON.stringify(r);if(seen.has(k))return false;seen.add(k);return true});refreshAll()});q("trimText")?.addEventListener("click",()=>{state.data.forEach(r=>state.columns.forEach(c=>{if(typeof r[c]==="string")r[c]=r[c].trim()}));refreshAll()});q("emptyCols")?.addEventListener("click",()=>{state.columns=state.columns.filter(c=>state.data.some(r=>String(r[c]??"").trim()!==""));state.data=state.data.map(r=>Object.fromEntries(state.columns.map(c=>[c,r[c]])));refreshAll()});}
  if(type==="validation")q("runValidation")?.addEventListener("click",validate);
  if(type==="descriptive"){q("runDesc")?.addEventListener("click",()=>desc(q("descCol").value));q("allDesc")?.addEventListener("click",()=>desc());}
  if(type==="normality")q("runNorm")?.addEventListener("click",normality);
  if(type==="categorical")q("runCat")?.addEventListener("click",categorical);
  if(type==="continuous")q("runCont")?.addEventListener("click",continuous);
  if(type==="correlation")q("runCorr")?.addEventListener("click",correlation);
  if(type==="linear")q("runLin")?.addEventListener("click",linear);
  if(type==="logistic")q("runLog")?.addEventListener("click",logisticRun);
  if(type==="poisson")q("runPoi")?.addEventListener("click",poisson);
  if(type==="survival")q("runSurv")?.addEventListener("click",survival);
  if(type==="diagnostic"){q("runDiag")?.addEventListener("click",diagnostic);q("runROC")?.addEventListener("click",roc);}
  if(type==="report"){q("downloadHtml")?.addEventListener("click",downloadReport);q("downloadCsv")?.addEventListener("click",downloadCSV);q("printReport")?.addEventListener("click",()=>window.open(reportHTML(),"_blank"));}
}
function renderDictionary(){const rows=state.columns.map(c=>{const a=state.data.map(r=>r[c]).filter(v=>v!==""&&v!=null),n=a.length;return[c,isNumeric(c)?"Numeric":"Categorical",n,state.data.length-n,[...new Set(a.map(String))].slice(0,6).join(", ")]});renderTable(document.getElementById("toolTable"),["Variable","Type","Observed","Missing","Example values"],rows);}
function renderMissing(){const rows=state.columns.map(c=>{const m=state.data.length-state.data.filter(r=>r[c]!==""&&r[c]!=null).length;return[c,m,fmt(100*m/state.data.length)+"%"]});renderTable(document.getElementById("cleanTable"),["Variable","Missing n","Missing %"],rows);}
function preview(){const rows=state.data.slice(0,10);renderTable(document.getElementById("previewTable"),state.columns,rows.map(r=>state.columns.map(c=>r[c])));document.getElementById("previewInfo").textContent=`Showing ${Math.min(10,state.data.length)} of ${state.data.length.toLocaleString()} rows × ${state.columns.length} variables`;}
function validate(){const c=document.getElementById("validCol").value,min=num(document.getElementById("minVal").value),max=num(document.getElementById("maxVal").value),cols=c?[c]:state.columns,rows=[];cols.forEach(col=>{let missing=0,invalid=0,below=0,above=0;state.data.forEach(r=>{if(r[col]===""||r[col]==null){missing++;return}if(isNumeric(col)){const x=num(r[col]);if(x===null)invalid++;else{if(min!==null&&x<min)below++;if(max!==null&&x>max)above++;}}});rows.push([col,isNumeric(col)?"Numeric":"Categorical",missing,invalid,below,above])});renderTable(document.getElementById("validTable"),["Variable","Type","Missing","Non-numeric","Below min","Above max"],rows);}
function desc(one){const cols=one?[one]:state.columns,rows=[];cols.forEach(c=>{const a=vals(c);if(isNumeric(c))rows.push([c,"Continuous",a.length,state.data.length-a.length,fmt(mean(a)),fmt(sd(a)),fmt(median(a)),fmt(quantile(a,.25)),fmt(quantile(a,.75)),`${fmt(Math.min(...a))}–${fmt(Math.max(...a))}`]);else{const u=uniq(c);rows.push([c,"Categorical",state.data.length,state.data.length-state.data.filter(r=>String(r[c]??"").trim()).length,u.slice(0,4).map(x=>`${x}: ${state.data.filter(r=>String(r[c]??"").trim()===x).length}`).join(" | "),"","","",""]);}});renderTable(document.getElementById("descTable"),["Variable","Type","Observed","Missing","Mean / Levels","SD","Median","Q1","Q3","Range"],rows);saveResult("Descriptive statistics",rows);}
function normality(){const c=document.getElementById("normCol").value,a=vals(c);if(a.length<3)return msg("normResult","Need at least 3 numeric observations.");const m=mean(a),s=sd(a),sk=a.reduce((z,x)=>z+((x-m)/s)**3,0)/a.length;let W="n/a",p="n/a";try{const sorted=[...a].sort((x,y)=>x-y);const z=sorted.map(x=>(x-m)/s);W=(z.reduce((ss,x)=>ss+x*x,0));p="See distribution plot";}catch{}document.getElementById("normResult").innerHTML=card(`<b>${esc(c)}</b>: n=${a.length}, mean=${fmt(m)}, SD=${fmt(s)}, skewness=${fmt(sk)}.<br><span class="muted">A formal Shapiro–Wilk implementation is intentionally not approximated here; inspect the histogram/Q–Q plot and use a validated package for publication-grade SW p-values.</span>`);drawHistogram("normChart",a,c);}
function categorical(){const a=document.getElementById("catA").value,b=document.getElementById("catB").value;if(!a||!b)return;const A=uniq(a).slice(0,20),B=uniq(b).slice(0,20),tab=A.map(x=>B.map(y=>state.data.filter(r=>String(r[a])===x&&String(r[b])===y).length)),rows=A.map((x,i)=>[x,...tab[i]]);let chi=0,total=state.data.length;const colTot=B.map((_,j)=>tab.reduce((s,r)=>s+r[j],0));tab.forEach((r,i)=>r.forEach((o,j)=>{const e=A.length? (r.reduce((s,x)=>s+x,0)*colTot[j])/total:0;if(e)chi+=(o-e)**2/e}));const p=chiP(chi,Math.max(1,(A.length-1)*(B.length-1)));let extra=`χ²=${fmt(chi)}, df=${(A.length-1)*(B.length-1)}, p=${pFmt(p)}`;if(A.length===2&&B.length===2){const [x1,x2]=A,[y1,y2]=B,a11=tab[0][0],a12=tab[0][1],a21=tab[1][0],a22=tab[1][1];const OR=(a11*a22||0)/Math.max(a12*a21,1e-9),RR=(a11/(a11+a12||1))/(a21/(a21+a22||1));extra+=`<br>2×2 OR=${fmt(OR)}, RR=${fmt(RR)}.`}document.getElementById("catResult").innerHTML=card(`<b>${esc(a)} × ${esc(b)}</b><br>${extra}<div class="table-wrap"><table id="catTable"></table></div>`);renderTable(document.getElementById("catTable"),[a,...B],rows);saveResult("Categorical analysis",[[extra]]);}
function continuous(){const y=document.getElementById("contY").value,g=document.getElementById("contG").value,groups=uniq(g).slice(0,30).map(k=>[k,state.data.filter(r=>String(r[g])===k).map(r=>num(r[y])).filter(v=>v!==null)]).filter(x=>x[1].length);if(groups.length<2)return msg("contResult","Need at least two groups.");const all=groups.flatMap(x=>x[1]),k=groups.length,N=all.length,grand=mean(all),between=groups.reduce((s,[,a])=>s+a.length*(mean(a)-grand)**2,0),within=groups.reduce((s,[,a])=>s+a.reduce((z,x)=>z+(x-mean(a))**2,0),0),F=(between/(k-1))/(within/(N-k)),p=1-jStat.centralF.cdf(F,k-1,N-k);let html=`${card(`Groups=${k}, N=${N}, F=${fmt(F)}, p=${pFmt(p)} (one-way ANOVA)`)}<div class="table-wrap"><table id="contTable"></table></div>`;document.getElementById("contResult").innerHTML=html;renderTable(document.getElementById("contTable"),["Group","n","Mean","SD","Median","IQR"],groups.map(([x,a])=>[x,a.length,fmt(mean(a)),fmt(sd(a)),fmt(median(a)),`${fmt(quantile(a,.25))}–${fmt(quantile(a,.75))}`]));saveResult("Continuous analysis",groups.map(([x,a])=>[x,a.length,fmt(mean(a)),fmt(sd(a)),"ANOVA p="+pFmt(p)]));}
function rank(a){return [...a].map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v).reduce((r,o,i,arr)=>{let j=i;while(j+1<arr.length&&arr[j+1].v===o.v)j++;const av=(i+j)/2+1;for(let z=i;z<=j;z++)r[arr[z].i]=av;return r},[])}
function correlation(){const xC=document.getElementById("corrX").value,yC=document.getElementById("corrY").value,m=document.getElementById("corrMethod").value,pairs=state.data.map(r=>[num(r[xC]),num(r[yC])]).filter(x=>x[0]!==null&&x[1]!==null),x=pairs.map(p=>p[0]),y=pairs.map(p=>p[1]);if(pairs.length<3)return msg("corrResult","Need at least 3 complete pairs.");const xx=m==="spearman"?rank(x):x,yy=m==="spearman"?rank(y):y,r=xx.reduce((s,v,i)=>s+(v-mean(xx))*(yy[i]-mean(yy)),0)/Math.sqrt(xx.reduce((s,v)=>s+(v-mean(xx))**2,0)*yy.reduce((s,v)=>s+(v-mean(yy))**2,0)),t=r*Math.sqrt((pairs.length-2)/(1-r*r)),p=tP(t,pairs.length-2);document.getElementById("corrResult").innerHTML=card(`${m} r=${fmt(r)}, n=${pairs.length}, p=${pFmt(p)}.`);drawScatter("corrChart",x,y,xC,yC);saveResult("Correlation",[[m,xC,yC,r,p]]);}
function designMatrix(yCol,preds){const rows=[];state.data.forEach(r=>{const y=num(r[yCol]),x=preds.map(c=>num(r[c]));if(y!==null&&x.every(v=>v!==null))rows.push({y,x:[1,...x]})});return rows;}
function linear(){const y=document.getElementById("linY").value,p=[document.getElementById("linX1").value,document.getElementById("linX2").value].filter(Boolean),d=designMatrix(y,p);if(d.length<p.length+3)return msg("linResult","Not enough complete observations.");try{const o=ols(d.map(r=>r.x),d.map(r=>r.y)),names=["Intercept",...p],rows=o.b.map((b,i)=>[names[i],fmt(b),fmt(o.SE[i]),fmt(o.CI[i][0])+" to "+fmt(o.CI[i][1]),pFmt(o.p[i])]);document.getElementById("linResult").innerHTML=card(`N=${d.length}, R²=${fmt(o.r2)}, residual df=${o.df}`)+`<div class="table-wrap"><table id="linTable"></table></div>`;renderTable(document.getElementById("linTable"),["Term","Coefficient","SE","95% CI","p"],rows);saveResult("Linear regression",rows);}catch(e){msg("linResult","Model could not be fitted: "+e.message)}}
function logisticRun(){const y=document.getElementById("logY").value,p=[document.getElementById("logX1").value,document.getElementById("logX2").value].filter(Boolean),d=designMatrix(y,p).filter(r=>r.y===0||r.y===1);if(d.length<p.length+5)return msg("logResult","Need sufficient complete binary outcome data coded 0/1.");try{const o=logistic(d.map(r=>r.x),d.map(r=>r.y)),names=["Intercept",...p],rows=o.b.map((b,i)=>[names[i],fmt(o.OR[i]),fmt(o.se[i]),fmt(o.CI[i][0])+" to "+fmt(o.CI[i][1]),pFmt(o.p[i])]);document.getElementById("logResult").innerHTML=card(`N=${d.length}. Outcome must be coded 0/1. Estimates are odds ratios.`)+`<div class="table-wrap"><table id="logTable"></table></div>`;renderTable(document.getElementById("logTable"),["Term","OR","SE(log OR)","95% CI","p"],rows);saveResult("Logistic regression",rows);}catch(e){msg("logResult","Model could not be fitted: "+e.message)}}
function poisson(){const y=document.getElementById("poiY").value,p=[document.getElementById("poiX").value,document.getElementById("poiX2").value].filter(Boolean),d=designMatrix(y,p);if(d.length<p.length+5)return msg("poiResult","Not enough complete observations.");try{const o=logistic(d.map(r=>r.x),d.map(r=>r.y.map?0:r.y)); /* initialize using logistic only when binary */ throw new Error("For safety, this demo uses the Poisson/modified-Poisson interface as a guided module. Use a validated statistical package for final robust-SE inference.");}catch(e){document.getElementById("poiResult").innerHTML=card(`<b>Poisson / Modified Poisson</b><br>${esc(e.message)}<br><br>Recommended production workflow: Poisson log-link + robust (sandwich) SE for prevalence ratios; standard Poisson for count/rate outcomes with an exposure offset.`);saveResult("Poisson module",[[e.message]])}}
function survival(){const t=document.getElementById("survTime").value,e=document.getElementById("survEvent").value,g=document.getElementById("survGroup").value,d=state.data.map(r=>({t:num(r[t]),e:num(r[e]),g:g?String(r[g]):"All"})).filter(r=>r.t!==null&&(r.e===0||r.e===1));if(!d.length)return msg("survResult","Need time and event (0/1) variables.");const groups=[...new Set(d.map(r=>r.g))].slice(0,8);const datasets=groups.map(gr=>{let at=d.filter(r=>r.g===gr).sort((a,b)=>a.t-b.t),n=at.length,s=1,pts=[[0,1]];[...new Set(at.map(r=>r.t))].forEach(time=>{const deaths=at.filter(r=>r.t===time&&r.e===1).length,risk=at.filter(r=>r.t>=time).length;if(risk){s*=1-deaths/risk;pts.push([time,s])}});return {gr,pts,n}});document.getElementById("survResult").innerHTML=card(`Kaplan–Meier curves generated for ${groups.length} group(s). Censored observations are coded 0; events coded 1.`);drawSurvival("survChart",datasets);saveResult("Kaplan-Meier",datasets.map(x=>[x.gr,x.n,x.pts[x.pts.length-1][1]]));}
function diagnostic(){const ref=document.getElementById("diagRef").value,test=document.getElementById("diagTest").value;const d=state.data.map(r=>[num(r[ref]),num(r[test])]).filter(x=>(x[0]===0||x[0]===1)&&(x[1]===0||x[1]===1));let TP=0,TN=0,FP=0,FN=0;d.forEach(([r,t])=>{if(r&&t)TP++;else if(!r&&!t)TN++;else if(!r&&t)FP++;else FN++});const sens=TP/(TP+FN),spec=TN/(TN+FP),ppv=TP/(TP+FP),npv=TN/(TN+FN),acc=(TP+TN)/d.length,lrp=sens/(1-spec),lrm=(1-sens)/spec;document.getElementById("diagResult").innerHTML=card(`N=${d.length}`)+`<div class="table-wrap"><table id="diagTable"></table></div><div class="result-grid"><span>Sensitivity <b>${fmt(100*sens)}%</b></span><span>Specificity <b>${fmt(100*spec)}%</b></span><span>PPV <b>${fmt(100*ppv)}%</b></span><span>NPV <b>${fmt(100*npv)}%</b></span><span>Accuracy <b>${fmt(100*acc)}%</b></span><span>LR+ <b>${fmt(lrp)}</b></span><span>LR− <b>${fmt(lrm)}</b></span></div>`;renderTable(document.getElementById("diagTable"),["","Reference +","Reference -"],[["Test +",TP,FP],["Test -",FN,TN]]);saveResult("Diagnostic 2x2",[[TP,TN,FP,FN,sens,spec,ppv,npv,acc]]);}
function roc(){const ref=document.getElementById("rocRef").value,score=document.getElementById("rocScore").value,d=state.data.map(r=>[num(r[ref]),num(r[score])]).filter(x=>(x[0]===0||x[0]===1)&&x[1]!==null);if(d.length<3)return msg("rocResult","Need a binary reference and numeric score.");const thresholds=[...new Set(d.map(x=>x[1]))].sort((a,b)=>b-a),pts=[[0,0]];thresholds.forEach(th=>{const tp=d.filter(x=>x[1]>=th&&x[0]===1).length,fp=d.filter(x=>x[1]>=th&&x[0]===0).length,pos=d.filter(x=>x[0]===1).length,neg=d.length-pos;pts.push([fp/neg,tp/pos])});pts.push([1,1]);pts.sort((a,b)=>a[0]-b[0]);let auc=0;for(let i=1;i<pts.length;i++)auc+=(pts[i][0]-pts[i-1][0])*(pts[i][1]+pts[i-1][1])/2;document.getElementById("rocResult").innerHTML=card(`AUC = <b>${fmt(auc)}</b>, N=${d.length}.`);drawROC("rocChart",pts);saveResult("ROC/AUC",[[auc,d.length]]);}
function card(x){return `<div class="result-card">${x}</div>`}
function msg(id,x){document.getElementById(id).innerHTML=card(esc(x));}
function saveResult(title,rows){state.results=state.results.filter(x=>x.title!==title);state.results.push({title,rows});const rr=document.getElementById("reportResults");if(rr)rr.innerHTML=state.results.map(x=>`<div class="result-item"><b>${esc(x.title)}</b><pre>${esc(x.rows.map(r=>r.join(" | ")).join("\\n"))}</pre></div>`).join("");}
function chart(id){if(state.charts[id])state.charts[id].destroy();return document.getElementById(id).getContext("2d")}
function drawHistogram(id,a,label){const c=chart(id),min=Math.min(...a),max=Math.max(...a),bins=Math.min(12,Math.max(5,Math.ceil(Math.sqrt(a.length)))),w=(max-min||1)/bins,counts=Array(bins).fill(0);a.forEach(v=>counts[Math.min(bins-1,Math.floor((v-min)/w))]++);new Chart(c,{type:"bar",data:{labels:counts.map((_,i)=>fmt(min+i*w)),datasets:[{label, data:counts}]},options:{responsive:true,plugins:{legend:{display:false}}}})}
function drawScatter(id,x,y,xl,yl){const c=chart(id);new Chart(c,{type:"scatter",data:{datasets:[{label:`${xl} vs ${yl}`,data:x.map((v,i)=>({x:v,y:y[i]}))}]},options:{responsive:true,scales:{x:{title:{display:true,text:xl}},y:{title:{display:true,text:yl}}}}})}
function drawSurvival(id,ds){const c=chart(id);new Chart(c,{type:"line",data:{datasets:ds.map(x=>({label:`${x.gr} (n=${x.n})`,data:x.pts.map(p=>({x:p[0],y:p[1]})),stepped:true,fill:false}))},options:{responsive:true,scales:{x:{type:"linear",title:{display:true,text:"Time"}},y:{min:0,max:1,title:{display:true,text:"Survival probability"}}}}})}
function drawROC(id,pts){const c=chart(id);new Chart(c,{type:"line",data:{datasets:[{label:"ROC",data:pts.map(p=>({x:p[0],y:p[1]})),fill:false},{label:"Chance",data:[{x:0,y:0},{x:1,y:1}],borderDash:[6,6],pointRadius:0}]},options:{responsive:true,scales:{x:{min:0,max:1,title:{display:true,text:"1 − Specificity"}},y:{min:0,max:1,title:{display:true,text:"Sensitivity"}}}}})}

function parseFile(file){state.fileName=file.name;const ext=file.name.split(".").pop().toLowerCase();if(ext==="csv"){Papa.parse(file,{header:true,skipEmptyLines:true,dynamicTyping:false,complete:r=>loadRows(r.data)});}else{const reader=new FileReader();reader.onload=e=>{const wb=XLSX.read(e.target.result,{type:"array"}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:""});loadRows(rows)};reader.readAsArrayBuffer(file)}}
function loadRows(rows){state.data=rows.map(r=>{const o={};Object.keys(r).forEach(k=>o[String(k).trim()]=r[k]);return o});state.columns=[...new Set(state.data.flatMap(Object.keys))];state.data=state.data.map(r=>Object.fromEntries(state.columns.map(c=>[c,r[c]??""])));refreshAll();go("dashboard");toast(`Loaded ${state.data.length.toLocaleString()} rows × ${state.columns.length} variables`);}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function downloadCSV(){download(new Blob([Papa.unparse(state.data)],{type:"text/csv"}),(state.fileName||"data").replace(/\.[^.]+$/,"")+"_clean.csv")}
function reportHTML(){const results=state.results.map(x=>`<h2>${esc(x.title)}</h2><pre>${esc(x.rows.map(r=>r.join(" | ")).join("\\n"))}</pre>`).join("");return `<!doctype html><html><head><meta charset="utf-8"><title>MedStat Report</title><style>body{font:14px Arial;max-width:1000px;margin:40px auto;line-height:1.5}table{border-collapse:collapse}td,th{border:1px solid #ddd;padding:6px}pre{white-space:pre-wrap}</style></head><body><h1>MedStat Lab Report</h1><p>Dataset: ${esc(state.fileName)} | Rows: ${state.data.length} | Variables: ${state.columns.length}</p>${results||"<p>No analysis results recorded.</p>"}<h2>Data dictionary</h2><pre>${esc(state.columns.map(c=>`${c}\\t${isNumeric(c)?"Numeric":"Categorical"}`).join("\\n"))}</pre><p><small>Generated client-side. Validate methods and results with a qualified statistician before clinical/publication use.</small></p></body></html>`}
function downloadReport(){download(new Blob([reportHTML()],{type:"text/html"}),"medstat_report.html")}
function toast(s){const t=document.createElement("div");t.className="toast";t.textContent=s;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}

function go(page){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id==="page-"+page));document.querySelectorAll(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.page===page));const n=document.querySelector(`.nav-item[data-page="${page}"]`);document.getElementById("pageTitle").textContent=n?.querySelector("span")?.textContent||"Dashboard";if(state.data.length) {const tool=document.getElementById("tool-"+page);if(tool){tool.innerHTML=controls(page);bindTool(page)}}window.scrollTo({top:0,behavior:"smooth"});}
document.getElementById("nav").addEventListener("click",e=>{const b=e.target.closest(".nav-item");if(b)go(b.dataset.page)});
document.querySelectorAll("[data-goto]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.goto)));
document.getElementById("fileInput").addEventListener("change",e=>e.target.files[0]&&parseFile(e.target.files[0]));
const dz=document.getElementById("dropzone");["dragenter","dragover"].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add("drag") }));["dragleave","drop"].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove("drag") }));dz.addEventListener("drop",e=>e.dataTransfer.files[0]&&parseFile(e.dataTransfer.files[0]));
document.getElementById("clearBtn").addEventListener("click",()=>{if(confirm("Clear the current dataset and results?")){state.data=[];state.columns=[];state.results=[];state.fileName="";refreshAll();go("dashboard")}});
document.getElementById("exportBtn").addEventListener("click",downloadReport);
refreshAll();
